version: '3.1'
services:
  stats-server:
    build: stats
    image: "stats_image:0.0.1"
    container_name: "stats_container"
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: "stats_db_container"
    ports:
      - "6431:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ewm
    image: "ewm_image:0.0.1"
    container_name: "ewm_container"
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5431/ewm
      - STATS_URL=http://stats:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: "ewm_db_container"
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm
